### ISSUE TITLE
aligned_alloc uses posix_memalign on MinGW

### ISSUE THREAD

**Issue by Lastique** [boostorg/align#10]
Legacy MinGW targets native Windows and does not provide `posix_memalign`.

Discovered by Boost.Atomic test [failures](https://ci.appveyor.com/project/Lastique/atomic/builds/31044903/job/lx00sgydy86nj0nv#L597).

**Comment by glenfe** [comment]
Thanks, I'll take care of this.

**Comment by glenfe** [comment]
Should be resolved in b8e81e1.
