### ISSUE TITLE
Provide align_up/align_down for arbitrary integers

### ISSUE THREAD

**Issue by Lastique** [boostorg/align#9]
It is sometimes useful to align integers other than `size_t` to a certain boundary. Using `size_t` regardless of the user's integer type is not possible if the type is larger than `size_t` (which is difficult to know portably given that `size_t` is platform-dependent).

**Comment by glenfe** [comment]
Implemented in 8caa2c0af075500a85e49745dafb509ba8c8ddcd

**Comment by Lastique** [comment]
Thanks!
